services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - mosquitto_network
      - timescaledb_network
    secrets:
      - mosquitto_ca_cert
      - mosquitto_client_cert
      - mosquitto_client_key
      - postgres_ca_cert
      - postgres_client_cert
      - postgres_client_key
    env_file:
      - .env
networks:
  mosquitto_network:
    external: true
  timescaledb_network:
    external: true
secrets:
  mosquitto_ca_cert:
    file: ./certs/mosquitto/ca.crt
  mosquitto_client_cert:
    file: ./certs/mosquitto/backend-client.crt
  mosquitto_client_key:
    file: ./certs/mosquitto/backend-client.key
  postgres_ca_cert:
    file: ./certs/postgres/ca.crt
  postgres_client_cert:
    file: ./certs/postgres/backend-client.crt
  postgres_client_key:
    file: ./certs/postgres/backend-client.key
