services:
  timescaledb:
    image: timescale/timescaledb:2.29.2-pg18-oss
    # restart: unless-stopped
    volumes:
      - timescaledb_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    secrets:
      - postgres_password
volumes:
  timescaledb_data:
secrets:
  postgres_password:
    file: ./postgres_password
