CREATE ROLE backend LOGIN;

GRANT CONNECT ON DATABASE air_compass TO backend;
GRANT USAGE ON SCHEMA public TO backend;

GRANT SELECT, INSERT, UPDATE, DELETE
ON ALL TABLES IN SCHEMA public
TO backend;

GRANT USAGE, SELECT, UPDATE
ON ALL SEQUENCES IN SCHEMA public
TO backend;
